---


# site
title: 'Alice & Mia'
email: 'hosts@aliceandmia.com'
description: 'Podcasts & Articles by Allison Washington & Miriam Suzanne'
location: 'home'
nav:
  - text: 'podcast'
    tag: 'Podcast'
  - text: 'writing'
    tag: 'Writing'
  - text: 'contact'
    url: '/contact/'
  - text: 'support'
    url: 'https://www.patreon.com/aliceandmia/'
tag_pages:
  - tag: 'Twined Fragments'
    slug: 'tag/twinedfragments'
  - tag: 'Writing'
    slug: 'tag/writing'
authors:
  - name: 'Allison Washington'
    url: 'http://www.allisonwashington.net'
  - name: 'Miriam Suzanne'
    url: 'http://www.miriamsuzanne.com'
footer_links:
  - text: 'Patreon'
    url: 'https://www.patreon.com/aliceandmia/'
  - text: 'Twined Fragments'
    url: 'https://medium.com/twinedfragments/'
  - text: 'Twitter'
    icon: 'twitter'
    url: 'https://twitter.com/aliceandmia/'


# settings
active_modules: [
  blog,
  current,
  denormalize_config,
  jinja_macros,
  pages,
  rst,
  tags,
  typogrify,
  uniqify,
  urls,
  wrap
  ]
canonical_url: 'http://www.aliceandmia.com/'
output_folder: '../docs'
template_path: '../templates'
modules:
  blog:
    index_url: '/'
